"use client";
import type { Cpu } from "@/data/types";
import { fmtMoney,perfDollar,perfWatt,totalCost } from "@/lib/metrics";
import { Panel,Title,selectStyle } from "./ui";
const delta=(a:number,b:number)=>b?Math.round((a/b-1)*100):0;
export function CpuCompare({pool,leftSku,rightSku,setLeftSku,setRightSku}:{pool:Cpu[];leftSku:string;rightSku:string;setLeftSku:(s:string)=>void;setRightSku:(s:string)=>void}){
 if(pool.length<2)return null;const left=pool.find(c=>c.sku===leftSku)||pool[0],right=pool.find(c=>c.sku===rightSku)||pool.find(c=>c.sku!==left.sku)||pool[0];
 const rows=[["Cores / CPU",left.cores,right.cores],["Max Turbo",`${left.maxTurboGHz} GHz`,`${right.maxTurboGHz} GHz`],["Cache",`${left.cacheMB} MB`,`${right.cacheMB} MB`],["TDP / CPU",`${left.tdpW} W`,`${right.tdpW} W`],["SPECint2017",left.specInt2017,right.specInt2017],["Configured Price",fmtMoney(totalCost(left)),fmtMoney(totalCost(right))],["Perf / $",perfDollar(left).toFixed(3),perfDollar(right).toFixed(3)],["Perf / Watt",perfWatt(left).toFixed(2),perfWatt(right).toFixed(2)]];
 return <Panel style={{marginTop:6}}><Title>Compare CPUs</Title><div style={{padding:10}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,alignItems:"center",marginBottom:7}}><b style={{fontSize:12}}>Metric</b><select value={left.sku} onChange={e=>setLeftSku(e.target.value)} style={selectStyle}>{pool.map(c=><option key={c.sku} value={c.sku}>Xeon {c.sku}</option>)}</select><select value={right.sku} onChange={e=>setRightSku(e.target.value)} style={selectStyle}>{pool.map(c=><option key={c.sku} value={c.sku}>Xeon {c.sku}</option>)}</select></div>{rows.map(r=><div key={String(r[0])} style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",fontSize:11,padding:"5px 0",borderTop:"1px solid rgba(97,145,175,.15)"}}><span>{r[0]}</span><span style={{textAlign:"center"}}>{r[1]}</span><span style={{textAlign:"center"}}>{r[2]}</span></div>)}<div style={{marginTop:7,fontSize:11,color:"#9fb0bd"}}>Right vs left: performance {delta(right.specInt2017,left.specInt2017)>0?"+":""}{delta(right.specInt2017,left.specInt2017)}% • price {delta(totalCost(right),totalCost(left))>0?"+":""}{delta(totalCost(right),totalCost(left))}%</div></div></Panel>
}