import React from "react";
import type { DealConfig,Filters,SystemModel,Workload } from "@/data/types";
import { cpuCatalog } from "@/data/cpus";import {defaultFilters,systems} from "@/data/systems";import {hardCompatible,filterFailures} from "@/lib/compatibility";import {specResult} from "@/data/specResults";import {Panel,Select} from "./ui";
export function FiltersPanel({pending,setPending,setFilters,deal}:{pending:Filters;setPending:(f:Filters)=>void;setFilters:(f:Filters)=>void;deal:DealConfig}){
 const specCatalog=cpuCatalog.filter(c=>Boolean(specResult(c.sku)));const hardPool=specCatalog.filter(c=>hardCompatible(c,pending,deal));const available=(patch:Partial<Filters>)=>hardPool.some(c=>filterFailures(c,{...pending,...patch},deal).length===0);
 const hasP=hardPool.some(c=>c.coreType==="P-Cores"),hasE=hardPool.some(c=>c.coreType==="E-Cores");const segments=[...new Set(hardPool.map(c=>c.segment))];const families=[...new Set(hardPool.map(c=>c.family))];const skuOptions: Array<[string,string,string?]>=specCatalog.sort((a,b)=>a.sku.localeCompare(b.sku,undefined,{numeric:true})).map(cpu=>{const compatible=hardPool.some(c=>c.sku===cpu.sku);return [cpu.sku,compatible?`Xeon ${cpu.sku}`:`Xeon ${cpu.sku} · Not available for selected system`,compatible?"":"disabled"]});
 const slider=(label:string,key:"minAvgCores"|"maxTdp"|"minSpec"|"maxRcp",min:number,max:number,step:number)=><div style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:4}}><span>{label}</span><span style={{border:"1px solid #38566d",borderRadius:4,padding:"4px 8px",background:"#071724"}}>{pending[key]}</span></div><input type="range" min={min} max={max} step={step} value={pending[key]} onChange={e=>setPending({...pending,[key]:Number(e.target.value)})} style={{width:"72%",accentColor:"#0969e8"}}/></div>;
 const preset=(p:Partial<Filters>)=>{const next={...pending,minAvgCores:0,minSpec:0,coreKind:"all" as const,sku:"all",family:"all",maxRcp:25000,scalability:"all" as const,tceOnly:false,...p};setPending(next);setFilters(next)};
 const activePreset=pending.tceOnly&&pending.workload==="any"?"tce":!pending.tceOnly&&pending.segment==="all"&&pending.workload==="any"?"value":!pending.tceOnly&&pending.workload==="hpc-ai"&&pending.segment==="all"?"performance":!pending.tceOnly&&pending.workload==="storage"&&pending.segment==="all"&&pending.maxTdp===250?"efficiency":"";
 const presetStyle=(key:string)=>({background:"#071724",border:"1px solid",borderColor:activePreset===key?"#18a8ff":"#25445c",boxShadow:activePreset===key?"0 0 7px rgba(24,168,255,.65)":"none",fontWeight:activePreset===key?700:400,width:"100%",minWidth:0,padding:"6px 3px",fontSize:10,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"clip"});
 const reset=()=>{const next={...defaultFilters,system:pending.system};setPending(next);setFilters(next)};
 return <Panel><div style={{padding:"9px 12px",borderBottom:"1px solid rgba(97,145,175,.25)",display:"flex",justifyContent:"space-between"}}><b>FILTERS</b><button onClick={reset} style={{background:"transparent",border:0,color:"#18a8ff"}}>Reset</button></div><div style={{padding:10}}>
 <div className="preset-grid"><button style={presetStyle("performance")} onClick={()=>preset({workload:"hpc-ai",segment:"all",tceOnly:false,maxTdp:400})}>Performance</button><button style={presetStyle("value")} onClick={()=>preset({workload:"any",segment:"all",tceOnly:false,maxTdp:400})}>Value</button><button style={presetStyle("tce")} onClick={()=>preset({workload:"any",segment:"all",tceOnly:true,maxTdp:400})}>TCE</button><button style={presetStyle("efficiency")} onClick={()=>preset({workload:"storage",segment:"all",tceOnly:false,maxTdp:250})}>Efficiency</button></div>
 <Select label="Optimize Choice" value={pending.workload} onChange={v=>setPending({...pending,workload:v as Workload})} opts={[["any","Optimize Choice"],["database","Database & Analytics"],["hpc-ai","HPC / AI"],["web","Web & Microservices"],["cloud","Cloud Native"],["storage","Infrastructure & Storage"]]}/>
 <Select label="System" value={pending.system} onChange={v=>{const sys=v as SystemModel;setPending({...pending,system:sys,coreKind:"all",segment:"all",tceOnly:false,sku:"all",family:"all",scalability:"all"})}} opts={Object.entries(systems).filter(([v])=>v!=="any").map(([v,x])=>[v,x.label])}/>
 <details className="advanced-filters" open><summary>Advanced Filters</summary><div style={{fontSize:10,color:"#18a8ff",fontWeight:800,letterSpacing:.5,margin:"8px 0 5px"}}>CPU SELECTION</div>
 <Select label="CPU SKU" value={pending.sku} onChange={v=>setPending({...pending,sku:v})} opts={[["all","Any compatible CPU"] as [string,string,string?],...skuOptions]}/>
 <div style={{fontSize:9,color:"#7890a2",margin:"-4px 0 7px 0"}}>Only CPUs with a validated Lenovo SPECint2017 result are available. Selecting a CPU and applying filters makes it the recommendation.</div>
 <Select label="CPU Family" value={pending.family} onChange={v=>setPending({...pending,family:v,sku:"all"})} opts={[["all","All CPU Families"],...families.map(f=>[f,f])]}/>
 <Select label="Max Scalability" value={pending.scalability} onChange={v=>setPending({...pending,scalability:v as Filters["scalability"],sku:"all"})} opts={[["all","Any Scalability"],["1S","1S"],["2S","2S"],["4S","4S"]]}/>
 {slider("Max Intel RCP / CPU ($)","maxRcp",500,25000,100)}
 <div style={{fontSize:10,color:"#18a8ff",fontWeight:800,letterSpacing:.5,margin:"8px 0 5px"}}>REQUIREMENTS</div>
 {slider("Min Cores / CPU","minAvgCores",0,172,1)}{slider("Max TDP / CPU (W)","maxTdp",35,400,5)}{slider("Min SPECint2017","minSpec",0,3000,10)}
 <Select label="Core Type" value={pending.coreKind} onChange={v=>setPending({...pending,coreKind:v as Filters["coreKind"]})} opts={[["all","All Core Types"],...(hasP&&available({coreKind:"p"})?[["p","P-Cores only"]]:[]),...(hasE&&available({coreKind:"e"})?[["e","E-Cores only"]]:[])]}/>
 <Select label="Top Choice Express" value={pending.tceOnly?"tce":"all"} onChange={v=>setPending({...pending,tceOnly:v==="tce"})} opts={[["all","All CPUs"],["tce","TCE only"]]}/>
 <Select label="Segment" value={pending.segment} onChange={v=>setPending({...pending,segment:v as Filters["segment"]})} opts={[["all","All Segments"],...segments.filter(s=>available({segment:s})).map(s=>[s,`${s} CPU`])]}/>
 <div style={{fontSize:10,color:"#7890a2",margin:"4px 0 8px"}}>CPU socket requirement comes from Deal Configuration.</div></details>
 <button className="action-feedback-button" onClick={()=>setFilters(pending)}><span className="button-label">Apply Filters</span><span className="button-working">Applying...</span></button>
 </div></Panel>
}
