import React from "react";
import type { DealConfig,Filters,SystemModel,Workload } from "@/data/types";
import { cpuCatalog } from "@/data/cpus";import {defaultFilters,systems} from "@/data/systems";import {hardCompatible,filterFailures} from "@/lib/compatibility";import {Panel,Select} from "./ui";
export function FiltersPanel({pending,setPending,setFilters,deal}:{pending:Filters;setPending:(f:Filters)=>void;setFilters:(f:Filters)=>void;deal:DealConfig}){
 const hardPool=cpuCatalog.filter(c=>hardCompatible(c,pending,deal));const available=(patch:Partial<Filters>)=>hardPool.some(c=>filterFailures(c,{...pending,...patch},deal).length===0);
 const hasP=hardPool.some(c=>c.coreType==="P-Cores"),hasE=hardPool.some(c=>c.coreType==="E-Cores");const segments=[...new Set(hardPool.map(c=>c.segment))];const families=[...new Set(hardPool.map(c=>c.family))];const skus=[...hardPool].sort((a,b)=>a.sku.localeCompare(b.sku,undefined,{numeric:true}));
 const slider=(label:string,key:"minAvgCores"|"maxTdp"|"minSpec"|"maxRcp",min:number,max:number,step:number)=><div style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:4}}><span>{label}</span><span style={{border:"1px solid #38566d",borderRadius:4,padding:"4px 8px",background:"#071724"}}>{pending[key]}</span></div><input type="range" min={min} max={max} step={step} value={pending[key]} onChange={e=>setPending({...pending,[key]:Number(e.target.value)})} style={{width:"72%",accentColor:"#0969e8"}}/></div>;
 const preset=(p:Partial<Filters>)=>{const next={...pending,minAvgCores:0,minSpec:0,coreKind:"all" as const,sku:"all",family:"all",maxRcp:25000,scalability:"all" as const,...p};setPending(next);setFilters(next)};
 const activePreset=pending.segment==="TCE"&&pending.workload==="any"?"tce":pending.segment==="all"&&pending.workload==="any"?"value":pending.workload==="hpc-ai"&&pending.segment==="all"?"performance":pending.workload==="storage"&&pending.segment==="all"&&pending.maxTdp===250?"efficiency":"";
 const presetStyle=(key:string)=>({background:"#071724",border:"1px solid",borderColor:activePreset===key?"#18a8ff":"#25445c",boxShadow:activePreset===key?"0 0 7px rgba(24,168,255,.65)":"none",fontWeight:activePreset===key?700:400,width:"100%",minWidth:0,padding:"6px 4px",fontSize:11,whiteSpace:"nowrap",overflow:"hidden"});
 const reset=()=>{const next={...defaultFilters,system:pending.system};setPending(next);setFilters(next)};
 return <Panel><div style={{padding:"9px 12px",borderBottom:"1px solid rgba(97,145,175,.25)",display:"flex",justifyContent:"space-between"}}><b>FILTERS</b><button onClick={reset} style={{background:"transparent",border:0,color:"#18a8ff"}}>Reset</button></div><div style={{padding:10}}>
 <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:5,marginBottom:9}}><button style={presetStyle("performance")} onClick={()=>preset({workload:"hpc-ai",segment:"all",maxTdp:400})}>Performance</button><button style={presetStyle("value")} onClick={()=>preset({workload:"any",segment:"all",maxTdp:400})}>Value</button><button style={presetStyle("tce")} onClick={()=>preset({workload:"any",segment:"TCE",maxTdp:400})}>TCE</button><button style={presetStyle("efficiency")} onClick={()=>preset({workload:"storage",segment:"all",maxTdp:250})}>Efficiency</button></div>
 <Select label="Optimize Choice" value={pending.workload} onChange={v=>setPending({...pending,workload:v as Workload})} opts={[["any","Optimize Choice"],["database","Database & Analytics"],["hpc-ai","HPC / AI"],["web","Web & Microservices"],["cloud","Cloud Native"],["storage","Infrastructure & Storage"]]}/>
 <Select label="System" value={pending.system} onChange={v=>{const sys=v as SystemModel;setPending({...pending,system:sys,coreKind:"all",segment:"all",sku:"all",family:"all",scalability:"all"})}} opts={Object.entries(systems).filter(([v])=>v!=="any").map(([v,x])=>[v,x.label])}/>
 <div style={{fontSize:10,color:"#18a8ff",fontWeight:800,letterSpacing:.5,margin:"8px 0 5px"}}>CPU SELECTION</div>
 <Select label="CPU SKU" value={pending.sku} onChange={v=>setPending({...pending,sku:v})} opts={[["all","Any compatible CPU"],...skus.map(cpu=>[cpu.sku,`Xeon ${cpu.sku}`])]}/>
 <Select label="CPU Family" value={pending.family} onChange={v=>setPending({...pending,family:v,sku:"all"})} opts={[["all","All CPU Families"],...families.map(f=>[f,f])]}/>
 <Select label="Max Scalability" value={pending.scalability} onChange={v=>setPending({...pending,scalability:v as Filters["scalability"],sku:"all"})} opts={[["all","Any Scalability"],["1S","1S"],["2S","2S"],["4S","4S"]]}/>
 {slider("Max Intel RCP / CPU ($)","maxRcp",500,25000,100)}
 <div style={{fontSize:10,color:"#18a8ff",fontWeight:800,letterSpacing:.5,margin:"8px 0 5px"}}>REQUIREMENTS</div>
 {slider("Min Cores / CPU","minAvgCores",0,172,1)}{slider("Max TDP / CPU (W)","maxTdp",35,400,5)}{slider("Min SPECint2017","minSpec",0,3000,10)}
 <Select label="Core Type" value={pending.coreKind} onChange={v=>setPending({...pending,coreKind:v as Filters["coreKind"]})} opts={[["all","All Core Types"],...(hasP&&available({coreKind:"p"})?[["p","P-Cores only"]]:[]),...(hasE&&available({coreKind:"e"})?[["e","E-Cores only"]]:[])]}/>
 <Select label="Segment" value={pending.segment} onChange={v=>setPending({...pending,segment:v as Filters["segment"]})} opts={[["all","All Segments"],...segments.filter(s=>available({segment:s})).map(s=>[s,s==="TCE"?"TCE":`${s} CPU`])]}/>
 <div style={{fontSize:10,color:"#7890a2",margin:"4px 0 8px"}}>CPU socket requirement comes from Deal Configuration.</div>
 <button onClick={()=>setFilters(pending)} style={{width:"100%",padding:9,border:0,borderRadius:4,background:"linear-gradient(180deg,#0878ff,#0758d8)",color:"white",fontWeight:700}}>Apply Filters</button>
 </div></Panel>
}