import type { Cpu, DealConfig, Filters } from "@/data/types";
import { systems } from "@/data/systems";
import { fmtMoney,pCores,eCores,totalCores,totalCost,totalTdp,maxSocketCount } from "@/lib/metrics";
import { recommendationReasons,scoreBreakdown,scoreCpu,workloadLabel } from "@/lib/scoring";
import { Mini,Panel,Title } from "./ui";
export function Recommendation({top,filters,pool,deal,onCompare}:{top:Cpu|null;filters:Filters;pool:Cpu[];deal:DealConfig;onCompare:()=>void}){
 const system=systems[filters.system];
 const quality=top?scoreBreakdown(top,pool):null;
 const cpuQty=deal.serverQty*deal.socketsPerServer;
 if(!top)return <Panel><Title color="#ff5252">Recommendation</Title><div style={{padding:16,color:"#d8e1e8"}}><h3 style={{margin:"0 0 8px",color:"#fff"}}>No compatible CPU found</h3><p style={{margin:0}}>The current filters return no compatible CPU. Relax budget, TDP, cores, segment or socket requirements.</p></div></Panel>;
 return <Panel><Title color="#38ff64">Recommendation</Title><div style={{padding:12}}><div style={{border:"1px solid #0b7039",borderRadius:7,padding:12,textAlign:"center",background:"rgba(4,55,37,.45)"}}><div style={{fontSize:26,color:"#39ff5f",fontWeight:900}}>Xeon {top.sku}</div><div style={{fontSize:12,color:"#58ff7a",marginTop:5}}>{top.family} • {top.codename} • {top.coreType}</div><div style={{fontSize:11,color:"#c9d6e0",marginTop:6}}>{system.label} • {workloadLabel(filters.workload)} • {top.segment}</div></div><div className="mini-grid" style={{marginTop:8}}><Mini label="P-Cores" value={pCores(top)}/><Mini label="E-Cores" value={eCores(top)}/><Mini label="Deal CPU Qty" value={cpuQty}/><Mini label="Max Turbo" value={`${top.maxTurboGHz} GHz`}/><Mini label="TDP / CPU" value={`${top.tdpW} W`}/><Mini label="Deal Cores" value={top.cores*cpuQty}/><Mini label="CPU Investment" value={fmtMoney(top.costUsd*cpuQty)}/><Mini label="Score" value={scoreCpu(top,filters)}/></div>{quality&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:5,marginTop:7}}>{Object.entries(quality).map(([k,v])=><div key={k} style={{textAlign:"center",padding:"5px 3px",border:"1px solid #25445c",borderRadius:5,fontSize:10}}><b style={{color:"#18a8ff"}}>{String(v)}</b><br/><span style={{textTransform:"capitalize",color:"#9fb0bd"}}>{k}</span></div>)}</div>}<div style={{fontSize:10,color:"#9fb0bd",marginTop:7}}>Maximum platform scalability: {maxSocketCount(top)}S. Price/TDP above use the CPU quantity defined by the catalog configuration, not maximum scalability.</div><button onClick={onCompare} style={{width:"100%",marginTop:8,fontWeight:800}}>COMPARE CPUs</button></div><div style={{borderTop:"1px solid rgba(97,145,175,.25)",padding:"10px 14px"}}><h3 style={{color:"#39ff5f",margin:"0 0 8px",fontSize:15}}>Why this CPU?</h3>{recommendationReasons(top,filters).map(x=><div key={x} style={{fontSize:12,margin:"7px 0"}}><span style={{color:"#46ff63",marginRight:8}}>✓</span>{x}</div>)}</div></Panel>
}