import type { Cpu, Filters } from "@/data/types";
import { systems } from "@/data/systems";
import { fmtMoney, pCores, eCores, totalCores, totalCost, totalTdp } from "@/lib/metrics";
import { scoreCpu, workloadLabel } from "@/lib/scoring";
import { Mini, Panel, Title } from "./ui";

export function Recommendation({ top, filters }: { top: Cpu | null; filters: Filters }) {
  const selectedSystem = systems[filters.system];
  if (!top) return <Panel><Title color="#ff5252">Recommendation</Title><div style={{ padding: 16, color: "#d8e1e8", lineHeight: 1.45 }}><h3 style={{ margin: "0 0 8px", color: "#fff" }}>No compatible CPU found</h3><p style={{ margin: 0 }}>Your current filter combination returns no CPUs. Try increasing budget/TDP, lowering minimum cores, changing Core Type, or selecting a compatible system.</p></div></Panel>;
  return <Panel><Title color="#38ff64">Recommendation</Title><div style={{ padding: 12 }}><div style={{ border: "1px solid #0b7039", borderRadius: 7, padding: 12, textAlign: "center", background: "rgba(4,55,37,.45)" }}><div style={{ fontSize: 26, color: "#39ff5f", fontWeight: 900 }}>Xeon {top.sku}</div><div style={{ fontSize: 12, color: "#58ff7a", marginTop: 5 }}>{top.family} • {top.codename} • {top.coreType}</div><div style={{ fontSize: 11, color: "#c9d6e0", marginTop: 6 }}>System: {selectedSystem.label} • Workload: {workloadLabel(filters.workload)}</div></div><div className="mini-grid" style={{ marginTop: 8 }}><Mini label="P-Cores" value={pCores(top)} /><Mini label="E-Cores" value={eCores(top)} /><Mini label="Total Cores" value={totalCores(top)} /><Mini label="Max Turbo" value={`${top.maxTurboGHz} GHz`} /><Mini label="TDP / Socket" value={`${top.tdpW} W`} /><Mini label="System TDP" value={`${totalTdp(top)} W`} /><Mini label="CPU Price" value={fmtMoney(totalCost(top))} /><Mini label="Score" value={scoreCpu(top, filters)} /></div></div><div style={{ borderTop: "1px solid rgba(97,145,175,.25)", padding: "10px 14px" }}><h3 style={{ color: "#39ff5f", margin: "0 0 8px", fontSize: 15 }}>Why this CPU?</h3>{[`Best ranked fit for ${workloadLabel(filters.workload)}`, `Validated for ${selectedSystem.label}`, `Strong ${top.coreType} alignment`, `Balanced score using SPECint, cores, value, efficiency and turbo`].map(x => <div key={x} style={{ fontSize: 12, margin: "7px 0" }}><span style={{ color: "#46ff63", marginRight: 8 }}>✓</span>{x}</div>)}</div></Panel>;
}
