import type { Cpu, DealConfig, Filters, SystemModel } from "@/data/types";
import { avgCores, maxSocketCount } from "./metrics";
import { systems } from "@/data/systems";
const entrySystems:SystemModel[]=["st50-v3","sr250-v3"];const rackSystems:SystemModel[]=["sr630-v4","sr650-v4","sr680a-v4","sr850-v4","sr860-v4"];
export function isEntryServerCpu(cpu:Cpu){return cpu.family==="Intel Pentium"||cpu.family==="Xeon E"||cpu.family==="Xeon 6300"||cpu.codename==="Raptor Lake"}
export function isRackServer(system:SystemModel){return rackSystems.includes(system)}
export function systemCompatible(cpu:Cpu,filters:Pick<Filters,"system">){if(filters.system==="any")return false;if(entrySystems.includes(filters.system))return isEntryServerCpu(cpu);if(isEntryServerCpu(cpu))return false;if(cpu.coreType==="E-Cores")return filters.system==="sr630-v4";if(cpu.coreType==="P-Cores"&&(cpu.family==="Xeon 6500"||cpu.family==="Xeon 6700"))return rackSystems.includes(filters.system);return false}
export function hardCompatible(cpu:Cpu,filters:Filters,deal?:DealConfig){if(!systemCompatible(cpu,filters))return false;const system=systems[filters.system];if(system.maxTdp&&cpu.tdpW>system.maxTdp)return false;if(deal&&deal.socketsPerServer>system.maxSockets)return false;if(deal&&maxSocketCount(cpu)<deal.socketsPerServer)return false;return true}
export function filterFailures(cpu:Cpu,filters:Filters,deal?:DealConfig){const failures:string[]=[];if(!hardCompatible(cpu,filters,deal))return ["Platform compatibility"];if(avgCores(cpu)<filters.minAvgCores)failures.push(`Min cores ${filters.minAvgCores}`);if(cpu.tdpW>filters.maxTdp)failures.push(`Max TDP ${filters.maxTdp}W`);if(cpu.specInt2017<filters.minSpec)failures.push(`Min SPECint ${filters.minSpec}`);if(filters.coreKind==="p"&&cpu.coreType!=="P-Cores")failures.push("P-Cores only");if(filters.coreKind==="e"&&cpu.coreType!=="E-Cores")failures.push("E-Cores only");if(filters.segment!=="all"&&cpu.segment!==filters.segment)failures.push(`Segment ${filters.segment}`);if(filters.tceOnly&&!cpu.tce)failures.push("Top Choice Express only");if(filters.sku!=="all"&&cpu.sku!==filters.sku)failures.push(`CPU ${filters.sku}`);if(filters.family!=="all"&&cpu.family!==filters.family)failures.push(`Family ${filters.family}`);if(cpu.costUsd>filters.maxRcp)failures.push(`Max RCP ${filters.maxRcp}`);if(filters.scalability!=="all"&&cpu.maxScalability!==filters.scalability)failures.push(`Scalability ${filters.scalability}`);return failures}
export function allowedByFilters(cpu:Cpu,filters:Filters,deal?:DealConfig){return filterFailures(cpu,filters,deal).length===0}
export function closestCompatible(cpus:Cpu[],filters:Filters,deal:DealConfig){return cpus.filter(c=>hardCompatible(c,filters,deal)).map(cpu=>({cpu,failures:filterFailures(cpu,filters,deal)})).filter(x=>x.failures.length).sort((a,b)=>a.failures.length-b.failures.length||b.cpu.specInt2017-a.cpu.specInt2017).slice(0,3)}

export function bestFallback(cpus:Cpu[],filters:Filters,deal:DealConfig,score:(cpu:Cpu)=>number){const platform=cpus.filter(c=>systemCompatible(c,filters)&&maxSocketCount(c)>=Math.min(deal.socketsPerServer,systems[filters.system].maxSockets));const candidates=platform.length?platform:cpus.filter(c=>systemCompatible(c,filters));if(!candidates.length)return null;return [...candidates].sort((a,b)=>{const af=filterFailures(a,filters,deal).filter(x=>x!=="Platform compatibility").length,bf=filterFailures(b,filters,deal).filter(x=>x!=="Platform compatibility").length;return af-bf||score(b)-score(a)})[0]||null}
